### ISSUE TITLE
Materials to go through

### ISSUE THREAD

**Issue by LukasSlouka** [ITU-MindMapper/MindMapper#1]
To get general idea read [wikipedia page](https://en.wikipedia.org/wiki/Mind_map).

Basics [tutorial](https://www.youtube.com/watch?v=wLWV0XN7K1g)

To get some inspiration watch [this lecture by Tony Buzan](https://www.youtube.com/watch?v=nMZCghZ1hB4) 

Existing software:
1 - [mindjet](https://www.mindjet.com/)
2 - [xmind](http://www.xmind.net/)
3 - [coggle](https://coggle.it/)
4 - [FreeMind](http://freemind.sourceforge.net/wiki/index.php/Main_Page)

**Comment by cibo94** [comment]
We can use [this design standard](https://www.google.com/design/spec/material-design/introduction.html#)

**Comment by cibo94** [comment]
Here are material icons we should use in our project:
https://github.com/google/material-design-icons

**Comment by cibo94** [comment]
Here is some docs about python and QML: http://pyqt.sourceforge.net/Docs/PyQt5/qml.html
